# Generated by Django 4.2.3 on 2023-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5)),
                ('nationality', models.CharField(default='Uzbek', max_length=55)),
                ('is_married', models.BooleanField(default=False)),
                ('birth_date', models.DateField(null=True, verbose_name='Birth date')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
