# Generated by Django 4.2.3 on 2023-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderproduct_remove_course_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
